### ISSUE TITLE
Remove `export(case_plot2)` from `NAMESPACE`

### ISSUE THREAD

**Issue by choisy** [biouea/covidhm#2]
The presence of `export(case_plot2)` in `NAMESPACE` prevents from loading the package. You may want to remove this instruction since these no `case_plot2()` function in your package anyway.

**Comment by biouea** [comment]
This is great, thanks Marc. We're in the process of incorporating an extensive and thorough set of reviewer comments, and should have added a note to the readme to this affect. Will sort out the installation issues now, but there might be a few other things that crop up over the next day or two. There will also be some differences between the results here and the preprint until we upload a new version (which will do very soon). If you have any question in the meantime, please let me know. Lewis.
