### ISSUE TITLE
Error Given in Initial Setup

### ISSUE THREAD

**Issue by scheffeh** [biouea/covidhm#3]
Hi there, first of all wanted to say thanks so much for putting together a tool like this, I think it's a great contribution to network studies. 

I was trying to just use the quickstart guide and I ran into this error both when I tried to plot the network or run a singular scenario: "Error: `size` must be less or equal than 0 (size of data), set `replace` = TRUE to use sampling with replacement"

It installed the package and the library fine as well as loading the association data you provide correctly from what I can tell. 

Any help would be greatly appreciated, or feel free to contact me at scheffeh@reed.edu if you have time. 

Thanks so much.

**Comment by scheffeh** [comment]
If it helps at all, this is the error code backtrace it gave me:
<error/rlang_error>
`size` must be less or equal than 0 (size of data), set `replace` = TRUE to use sampling with replacement.
Backtrace:
     █
  1. ├─covidhm::plot_network(...)
  2. │ └─covidhm::outbreak_model(...)
  3. │   └─covidhm::outbreak_step(...)
  4. │     └─new_cases[infected, ] %>% group_by(contact) %>% sample_n(1)
  5. │       ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  6. │       └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  7. │         └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  8. │           └─covidhm:::`_fseq`(`_lhs`)
  9. │             └─magrittr::freduce(value, `_function_list`)
 10. │               ├─base::withVisible(function_list[[k]](value))
 11. │               └─function_list[[k]](value)
 12. │                 ├─dplyr::sample_n(., 1)
 13. │                 └─dplyr:::sample_n.data.frame(., 1)
 14. │                   ├─dplyr::slice(...)
 15. │                   └─dplyr:::slice.data.frame(...)
 16. │                     └─dplyr:::slice_rows(.data, ...)
 17. │                       └─mask$eval_all(quo)
 18. ├─rlang:::sample.int(...)
 19. ├─base::sample.int(...)
 20. └─dplyr:::check_size(1, n(), replace = replace)
 21.   └─dplyr:::bad_args(...)
 22.     └─dplyr:::glubort(fmt_args(args), ..., .envir = .envir)

Apologies if I'm not explaining this right or if it's an obvious problem because I'm pretty new to using other people's packages in R. Thanks!

**Comment by rfbrondum** [comment]
I had similar problems running the code out of the box. It seems the first infected (which is fixed by a random seed) does not always infect its contact causing the code to break when sampling from an empty set. I replaced the following lines (170-172) in outbreak_step.R 

```
new_cases <- new_cases[infected,] %>%  
    group_by(contact) %>%  
    sample_n(1)  
 ```

with

```
if(any(infected)){
      new_cases <- new_cases[infected,] %>%
        group_by(contact) %>%
        sample_n(1)
    }
```

**Comment by biouea** [comment]
Thanks all for flagging this (and for this suggested fix). I am totally snowed under right now but will get this sorted ASAP.

Lewis

**Comment by biouea** [comment]
Ok should now be fixed - let me know if any further issues
